{{- define "myservice.name" -}}
{{- .Chart.Name | trunc 63 | trimSuffix "-" -}}
{{- end }}

{{- define "myservice.fullname" -}}
{{- printf "%s-%s" .Release.Name (include "myservice.name" .) | trunc 63 | trimSuffix "-" -}}
{{- end }}

{{- define "myservice.labels" -}}
app.kubernetes.io/name: {{ include "myservice.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
helm.sh/chart: {{ printf "%s-%s" .Chart.Name (.Chart.Version | replace "+" "_") }}
{{- end }}

{{- define "myservice.selectorLabels" -}}
app.kubernetes.io/name: {{ include "myservice.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
